version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000
        VARIANT: 18

    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ..:/workspace:cached

    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

    links:
      - sql
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "YourStrongPassword!"
